# Generated by Django 2.1.8 on 2019-04-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_tweet_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='date',
        ),
    ]
